// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3NKCJ7NdnffNtmjOaRZHNft8H0sfqVZQ',
    appId: '1:316804164575:web:291adc9a55908ae723b26a',
    messagingSenderId: '316804164575',
    projectId: 'fruit-hub-dashboard',
    authDomain: 'fruit-hub-dashboard.firebaseapp.com',
    storageBucket: 'fruit-hub-dashboard.firebasestorage.app',
    measurementId: 'G-C80RHPXFE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCsnBG68pwvdW2aiWYyQ4CxtjLwyprHMs',
    appId: '1:316804164575:android:a9adbc8a4472a78823b26a',
    messagingSenderId: '316804164575',
    projectId: 'fruit-hub-dashboard',
    storageBucket: 'fruit-hub-dashboard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlrVffFqXFLpE5nfRKRvYd7Tz8QPqBJp0',
    appId: '1:316804164575:ios:352d322ff3d0a21b23b26a',
    messagingSenderId: '316804164575',
    projectId: 'fruit-hub-dashboard',
    storageBucket: 'fruit-hub-dashboard.firebasestorage.app',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlrVffFqXFLpE5nfRKRvYd7Tz8QPqBJp0',
    appId: '1:316804164575:ios:352d322ff3d0a21b23b26a',
    messagingSenderId: '316804164575',
    projectId: 'fruit-hub-dashboard',
    storageBucket: 'fruit-hub-dashboard.firebasestorage.app',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3NKCJ7NdnffNtmjOaRZHNft8H0sfqVZQ',
    appId: '1:316804164575:web:d64c8865f41df29823b26a',
    messagingSenderId: '316804164575',
    projectId: 'fruit-hub-dashboard',
    authDomain: 'fruit-hub-dashboard.firebaseapp.com',
    storageBucket: 'fruit-hub-dashboard.firebasestorage.app',
    measurementId: 'G-Q1WLTT22NE',
  );
}
