// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRgqN8pOMzWgmiswxwnqS_BAV6y10hbt0',
    appId: '1:19068153025:web:27f557991c06f8f9ce3840',
    messagingSenderId: '19068153025',
    projectId: 'e-commerce-app-e4e99',
    authDomain: 'e-commerce-app-e4e99.firebaseapp.com',
    storageBucket: 'e-commerce-app-e4e99.firebasestorage.app',
    measurementId: 'G-4EKNPJVMRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm5lCkvBndYiektWEow8-WS-JE3tpHmFQ',
    appId: '1:19068153025:android:0a0bdbed9f6867d4ce3840',
    messagingSenderId: '19068153025',
    projectId: 'e-commerce-app-e4e99',
    storageBucket: 'e-commerce-app-e4e99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9dRXIFgTwkRuiJJ_mmydgaMZz71CWyr0',
    appId: '1:19068153025:ios:de049d9bc465f3c8ce3840',
    messagingSenderId: '19068153025',
    projectId: 'e-commerce-app-e4e99',
    storageBucket: 'e-commerce-app-e4e99.firebasestorage.app',
    androidClientId:
        '19068153025-k3d0lhoj31edjnetqvbtvr2i3c4lkdce.apps.googleusercontent.com',
    iosClientId:
        '19068153025-9ug7l6n1tk36k9r64pepi1co8q0291ao.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9dRXIFgTwkRuiJJ_mmydgaMZz71CWyr0',
    appId: '1:19068153025:ios:de049d9bc465f3c8ce3840',
    messagingSenderId: '19068153025',
    projectId: 'e-commerce-app-e4e99',
    storageBucket: 'e-commerce-app-e4e99.firebasestorage.app',
    androidClientId:
        '19068153025-k3d0lhoj31edjnetqvbtvr2i3c4lkdce.apps.googleusercontent.com',
    iosClientId:
        '19068153025-9ug7l6n1tk36k9r64pepi1co8q0291ao.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRgqN8pOMzWgmiswxwnqS_BAV6y10hbt0',
    appId: '1:19068153025:web:ab941bf20268e03ece3840',
    messagingSenderId: '19068153025',
    projectId: 'e-commerce-app-e4e99',
    authDomain: 'e-commerce-app-e4e99.firebaseapp.com',
    storageBucket: 'e-commerce-app-e4e99.firebasestorage.app',
    measurementId: 'G-DD55T4V9MX',
  );
}
